# Generated by Django 2.0 on 2017-12-16 21:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/%Y-%m-%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_hotdog', models.BooleanField(default=False)),
                ('computed_status',
                 models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'in progress'), (2, 'completed')],
                                                  default=None, null=True)),
                ('author',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nothotdog.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nothotdog.Tag'),
        ),
        migrations.AddField(
            model_name='picture',
            name='tags',
            field=models.ManyToManyField(through='nothotdog.Score', to='nothotdog.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('picture', 'tag')},
        ),
    ]
