# Generated by Django 2.0 on 2017-12-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nothotdog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='computed_status',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'pending'), (1, 'in progress'), (2, 'completed'), (2, 'error')], default=None, null=True),
        ),
    ]
