# Generated by Django 2.0 on 2017-12-16 23:10

from django.db import migrations, models

import nothotdog.utils


class Migration(migrations.Migration):
    dependencies = [
        ('nothotdog', '0002_auto_20171216_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(
                upload_to=nothotdog.utils.PathAndRename('/home/mm/Projects/nothotdog/backend/mediafiles/images')),
        ),
    ]
