# Generated by Django 2.0 on 2017-12-17 01:31

from django.db import migrations, models

import nothotdog.utils


class Migration(migrations.Migration):
    dependencies = [
        ('nothotdog', '0003_auto_20171216_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=nothotdog.utils.PathAndRename('images')),
        ),
    ]
