# Generated by Django 2.0 on 2017-12-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nothotdog', '0006_auto_20171217_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
        migrations.AlterField(
            model_name='picture',
            name='computed_status',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'pending'), (1, 'in progress'), (2, 'completed'), (3, 'error'), (4, 'force')], default=4),
        ),
        migrations.AlterField(
            model_name='picture',
            name='is_hotdog',
            field=models.BooleanField(default=False, verbose_name='Is Hot Dog?'),
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.FloatField(default=0, verbose_name='Score'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('picture', 'tag')},
        ),
    ]
