# Generated by Django 2.0 on 2017-12-17 04:26

from django.db import migrations, models

import nothotdog.utils


class Migration(migrations.Migration):
    dependencies = [
        ('nothotdog', '0007_auto_20171217_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='watermark_image',
            field=models.ImageField(blank=True, default=None, null=True,
                                    upload_to=nothotdog.utils.PathAndRename('watermark')),
        ),
    ]
