# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nothotdog', '0008_picture_watermark_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
